export const BATTLE_DETAIL = 'BATTLE_DETAIL';
export const CURRENT_USER = 'CURRENT_USER';
export const BATTLE_LIST = 'BATTLE_LIST';
export const BATTLE_CREATE = 'BATTLE_CREATE';
export const TEAM_CREATE = 'TEAM_CREATE';
export const GET_POKEMONS_FROM_API = 'GET_POKEMONS_FROM_API';
export const POKEMON_LIST = 'POKEMON_LIST';
