export const BATTLE_DETAIL = 'BATTLE_DETAIL';
export const CURRENT_USER = 'CURRENT_USER';
export const BATTLE_LIST = 'BATTLE_LIST';
export const BATTLE_CREATE = 'BATTLE_CREATE';
export const TEAM_CREATE = 'TEAM_CREATE';
export const POKEMON_CHANGE_INDEX = 'POKEMON_CHANGE_INDEX';
