# Generated by Django 3.2 on 2021-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20210504_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_id',
            field=models.IntegerField(null=True),
        ),
    ]
