# Generated by Django 3.2 on 2021-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20210611_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
