# Generated by Django 3.2 on 2021-04-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battle',
        ),
    ]
