# Generated by Django 2.2.19 on 2021-03-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_gamer', to=settings.AUTH_USER_MODEL, verbose_name='Digite seu nome:'),
        ),
    ]
