# Generated by Django 3.2 on 2021-04-28 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0002_delete_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pk1_creator', models.CharField(max_length=200, null=True)),
                ('pk2_creator', models.CharField(max_length=200, null=True)),
                ('pk3_creator', models.CharField(max_length=200, null=True)),
                ('pk1_opponent', models.CharField(max_length=200, null=True)),
                ('pk2_opponent', models.CharField(max_length=200, null=True)),
                ('pk3_opponent', models.CharField(max_length=200, null=True)),
                ('winner', models.CharField(max_length=200, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
