# Generated by Django 3.2 on 2021-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_alter_pokemonteam_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='opponent',
            field=models.CharField(max_length=200),
        ),
    ]
