# Generated by Django 3.2 on 2021-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_alter_pokemonteam_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonteam',
            options={},
        ),
        migrations.RenameField(
            model_name='pokemonteam',
            old_name='order',
            new_name='position_pokemon_1',
        ),
        migrations.AddField(
            model_name='pokemonteam',
            name='position_pokemon_2',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonteam',
            name='position_pokemon_3',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
