# Generated by Django 2.2.19 on 2021-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20210322_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='pk11',
            field=models.CharField(max_length=200, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk12',
            field=models.CharField(max_length=200, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk21',
            field=models.CharField(max_length=200, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk22',
            field=models.CharField(max_length=200, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk31',
            field=models.CharField(max_length=200, verbose_name='Pokemon 3:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk32',
            field=models.CharField(max_length=200, verbose_name='Pokemon 3:'),
        ),
    ]
