# Generated by Django 3.2 on 2021-07-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20210707_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonteam',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='pokemonteam',
            old_name='position_pokemon_1',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='pokemonteam',
            name='position_pokemon_2',
        ),
        migrations.RemoveField(
            model_name='pokemonteam',
            name='position_pokemon_3',
        ),
    ]
