# Generated by Django 2.2.19 on 2021-03-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_auto_20210322_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='id_batalha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batalha_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk11',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk12',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk21',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk22',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk31',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pk32',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
    ]
