# Generated by Django 2.2.19 on 2021-03-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_auto_20210322_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='winner',
        ),
        migrations.AddField(
            model_name='battle',
            name='pk11',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk12',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk21',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk22',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk31',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk32',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
    ]
