# Generated by Django 2.2.19 on 2021-03-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_auto_20210322_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='id',
            new_name='teste',
        ),
    ]
