# Generated by Django 2.2.19 on 2021-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0012_auto_20210322_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='pk11',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk12',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk21',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk22',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk31',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk32',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
    ]
