# Generated by Django 2.2.19 on 2021-03-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0013_auto_20210323_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='pk11',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='pk12',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='pk21',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='pk22',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='pk31',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='pk32',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player2',
        ),
        migrations.AddField(
            model_name='battle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk1_creator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk1_opponent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk2_creator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk2_opponent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk3_creator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk3_opponent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
