# Generated by Django 2.2.19 on 2021-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0015_battle_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
